### ISSUE TITLE
Slow scan missing

### ISSUE THREAD

**Issue by urostrickovic** [alchem1ster/WotLK-Auctionator#4]
I am playing on Warmane-Onyxia server. I used addon from felbite for WoW 3.3.5, and it had option to start a full slow scan by pressing the Control button. Then I downloaded this addon and replaced felbite's one. It also had a slow scan, but the database was wrong. So i removed it completeley, cleaned lua files and installed it again. Now it can only do full scan that last about 30 seconds and doesn't get all auctions. 
Does this addon have SLOW scan by pressing CONTROL on keyboard or is it problem on my end?
![Untitled (1)](https://github.com/alchem1ster/WotLK-Auctionator/assets/48966542/ae705ad8-d450-42d4-92fb-e583ea045253)

**Comment by alchem1ster** [comment]
>Does this addon have SLOW scan by pressing CONTROL on keyboard

Nope. Not supported here.
