### ISSUE TITLE
Full scan freezes and throws neverending loop of errors.

### ISSUE THREAD

**Issue by TheBeardOfTruth** [alchem1ster/WotLK-Auctionator#5]
So I'm trying this version because the other version I had didn't scan more than a page (50) items, arguably this is worse.

![Screenshot_2024-08-24_20-43-19](https://github.com/user-attachments/assets/aba2b8ff-589b-4cab-ad5a-382f79c15a1f)

Addons enabled:
- Auctionator

Server:
- Chromiecraft (AzerothCore)

Expected result:
- Full scan should scan items and not get stuck in infinite errors

**Comment by alchem1ster** [comment]
ChromieCraft doesn't support Full Scan feature on server-side (CC administration decision)
Only 50 items scan per page (slow scan), which is not supported by this version of the addon.
